In [1]:
from cust_dataset import CustDataset

from torchvision import transforms

In [2]:
data = CustDataset(transform = 
                        transforms.Compose([
                            transforms.RandomHorizontalFlip()
                            ]),train=True)

Initializing CustomDataset 1
Number of rows selected: 100
Loaded labels...
sss done
CustomDataset initialized.


In [10]:
data.vars['tfmri_nb_all_beh_ctotal_mrt_normalised']

src_subject_id
NDARINV005V6D2C    0.216762
NDARINV007W6H7B    0.664711
NDARINV00CY2MDM    0.633248
NDARINV00HEV6HB    0.571336
NDARINV00LJVZK2    0.571497
                     ...   
NDARINV0BVP2PTD    0.385129
NDARINV0BXXNBH4    0.582933
NDARINV0C471G23    0.485788
NDARINV0C765WK4    0.390668
NDARINV0CBFTKR7    0.823856
Name: tfmri_nb_all_beh_ctotal_mrt_normalised, Length: 100, dtype: float64

In [4]:
train_data = CustDataset(transform = 
                        transforms.Compose([
                            transforms.RandomHorizontalFlip()
                            ]),train=True)
test_data = CustDataset(train=False,valid=False)
# print(len(test_data.test_idx))

Initializing CustomDataset 1
Number of rows selected: 200
Loaded labels...
sss done
CustomDataset initialized.
Initializing CustomDataset 1
Number of rows selected: 200
Loaded labels...
sss done
CustomDataset initialized.
Initializing CustomDataset 1
Number of rows selected: 200
Loaded labels...
sss done
CustomDataset initialized.


In [15]:
from torch.utils.data.sampler import SubsetRandomSampler

In [17]:
train_sampler = SubsetRandomSampler(train_data.train_idx)
test_sampler = SubsetRandomSampler(test_data.test_idx)

In [18]:
from torch.utils.data import DataLoader


In [24]:
train_loader = DataLoader(train_data,batch_size=10, 
                                sampler= train_sampler, num_workers=4)

test_loader = DataLoader(test_data,batch_size=10,
                                sampler= test_sampler, num_workers=4)
# print(valid_data.vars.tfmri_nb_all_beh_ctotal_mrt_normalised.values)

[0.21676181 0.66471115 0.63324766 0.5713358  0.57149662 0.7577393
 0.57232634 0.61050847 0.47869976 0.51985101 0.53997735 0.37059094
 0.60708203 0.66142549 0.6729254  0.35087163 0.58665731 0.62656841
 0.66991805 0.46521512 0.53951311 0.49214146 0.50427442 0.47868265
 0.91581694 0.42208784 0.43668389 0.32992534 0.59487053 0.5282757
 0.44143295 0.50994597 0.6116105  0.51132372 0.48236061 0.61028327
 0.59409205 0.76070599 0.43415927 0.56169644 0.53289207 0.62896537
 0.37479436 0.47714711 0.45236903 0.44394289 0.30892307 0.5700276
 0.28259998 0.58507525 0.5021404  0.58850934 0.5238485  0.30032808
 0.59128386 0.41683087 0.50407409 0.40730873 0.39579211 0.83310705
 0.45373871 0.6144514  0.4811114  0.34226829 0.38972743 0.54549302
 0.56584067 0.61209719 0.50058417 0.54000593 0.5537693  0.47706506
 0.43992347 0.51654233 0.4525863  0.38823965 0.45403081 0.48694961
 0.5019324  0.48281998 0.52053188 0.37912244 0.5531325  0.58137635
 0.36515862 0.4658948  0.3813442  0.58295918 0.53155548 0.4843096

In [ ]:
for X, y in train_loader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

Shape of X [N, C, H, W]: torch.Size([10, 182, 218, 182])
Shape of y: torch.Size([10]) torch.float64


In [ ]:
# import torch

# device = (
#     "cuda"
#     if torch.cuda.is_available()
#     else "mps"
#     if torch.backends.mps.is_available()
#     else "cpu"
# )
# print(f"Using {device} device")

import torch

device = (
    "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")


Using cpu device


In [ ]:
from network import Network

model = Network().to(device)
print(model)

Network(
  (cv1): Conv3d(1, 32, kernel_size=(3, 3, 3), stride=(1, 1, 1))
  (bn1): BatchNorm3d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (cv2): Conv3d(32, 64, kernel_size=(3, 3, 3), stride=(1, 1, 1))
  (bn2): BatchNorm3d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (cv3): Conv3d(64, 128, kernel_size=(3, 3, 3), stride=(1, 1, 1))
  (bn3): BatchNorm3d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (cv4): Conv3d(128, 256, kernel_size=(3, 3, 3), stride=(1, 1, 1))
  (bn4): BatchNorm3d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (cv5): Conv3d(256, 256, kernel_size=(3, 3, 3), stride=(1, 1, 1))
  (bn5): BatchNorm3d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (pool): MaxPool3d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (fc1): Linear(in_features=9216, out_features=1, bias=True)
  (d3d): Dropout3d(p=0.2, inplace=False)
  (layer2): Sequential(
   

In [ ]:
import torch.nn as nn

loss_fn = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

In [ ]:
def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader)
    print("train size", size)
    model.train()
    train_loss = 0
    # with torch.no_grad():
    for X, y in dataloader:
        X, y = X.to(device).float(), y.to(device).float()
        X = torch.unsqueeze(X, 1).float() 
        pred = model(X)
        pred = pred.squeeze()  
        loss = loss_fn(pred, y)
        train_loss += loss.item()

        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        
    avg_train_loss = train_loss / len(dataloader)
    print(f"Average train loss: {avg_train_loss}")


In [ ]:
def test(dataloader, model, loss_fn):
    size = len(dataloader)
    print("test size", size)
    model.eval()
    test_loss = 0
    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device).float(), y.to(device).float()
            X = torch.unsqueeze(X, 1).float() 
            pred = model(X)
            pred = pred.squeeze()  
            test_loss += loss_fn(pred, y).item()

    avg_test_loss = test_loss / len(dataloader)
    print(f"Average test loss: {avg_test_loss}")


In [ ]:
model = model.double().to(device)
model = model.float()  # Ensure the model is in float

In [ ]:
def validate(dataloader, model, loss_fn):
    size = len(dataloader)
    num_batches = len(dataloader)
    model.eval()
    total_loss, correct = 0, 0
    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            X, y = X.float(), y.float()  
            X = torch.unsqueeze(X, 1).float()

            pred = model(X)
            total_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()

    avg_loss = total_loss / num_batches
    accuracy = correct / size
    print(f"Validation Error: \n Accuracy: {(100*accuracy):>0.1f}%, Avg loss: {avg_loss:>8f} \n")
    return avg_loss, accuracy

In [ ]:
epochs = 5
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_loader, model, loss_fn, optimizer)
    test(test_loader, model, loss_fn)
print("Done!")

Epoch 1
-------------------------------
train size 16
Average train loss: 3.42129001673311
test size 4
Average test loss: 1.2657445669174194
Epoch 2
-------------------------------
train size 16
Average train loss: 0.3663286631926894
test size 4
Average test loss: 1.2589514255523682
Epoch 3
-------------------------------
train size 16
Average train loss: 0.1251244021113962
test size 4
Average test loss: 0.4760708659887314
Epoch 4
-------------------------------
train size 16
Average train loss: 0.13724293652921915
test size 4
Average test loss: 0.11718388460576534
Epoch 5
-------------------------------
train size 16
Average train loss: 0.12132254987955093
test size 4
Average test loss: 0.0278573390096426
Done!


In [ ]:
X, y = next(iter(train_loader))
X, y = X.to(device).float(), y.to(device).float()
X = torch.unsqueeze(X, 1).float() 
pred = model(X)
# pred = pred.squeeze()

In [ ]:
pred,y

(tensor([[0.4604],
         [0.4926],
         [0.3295],
         [0.5661],
         [0.5211],
         [0.4865],
         [0.4909],
         [0.3973],
         [0.4397],
         [0.5174]], grad_fn=<AddmmBackward0>),
 tensor([0.4891, 0.4828, 0.3971, 0.4204, 0.5913, 0.5021, 0.5512, 0.4463, 0.3882,
         0.3791]))

In [ ]:
loss = loss_fn(pred, y)
# train_loss += loss.item()

/home/users/schitikesi1/miniconda3/lib/python3.11/site-packages/torch/nn/modules/loss.py:535: UserWarning: Using a target size (torch.Size([10])) that is different to the input size (torch.Size([10, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [ ]:
loss

tensor(0.0088, grad_fn=<MseLossBackward0>)

In [ ]:
X, y = next(iter(test_loader))
X, y = X.to(device).float(), y.to(device).float()
X = torch.unsqueeze(X, 1).float() 
pred = model(X)

In [ ]:
pred, y

(tensor([[0.3515],
         [0.4234],
         [0.4239],
         [0.3931],
         [0.4084],
         [0.4451],
         [0.4081],
         [0.4375],
         [0.4330],
         [0.2377]], grad_fn=<AddmmBackward0>),
 tensor([0.5416, 0.3907, 0.4540, 0.3003, 0.4999, 0.4070, 0.6376, 0.5702, 0.5041,
         0.4537]))